version: 2

# Automate weekly SHA updates for pinned GitHub Actions workflows.
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    commit-message:
      prefix: "[chore][ci]"
    labels:
      - dependencies
    groups:
      actions:
        patterns:
          - "*"
